# These are supported funding model platforms
github: [Pericena]
paypal: https://www.paypal.com/paypalme/lpericena  # Reemplaza "link_paypal" con tu enlace de PayPal
binance: 198690745  # Reemplaza "link_binance" con tu enlace de Binance
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # username_ko_fi
tidelift: # Ejemplo: npm/babel
liberapay: # Replace with a single Liberapay username username_liberapay
issuehunt: # Replace with a single Otechie username username_issuehunt
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry project-name_lfx_crowdfunding  # Ejemplo: cloud-foundry
custom: ['https://lpericena.blogspot.com/', 'https://github.com/sponsors/Pericena']
